### PR TITLE
`observability`: add a missed feature to `tower-http` dep

### PR DESCRIPTION
**Pull request by s373r**
### Fixed
- `observability`: fixed build when using the crate as an external dependency

### CODE REVIEW

File: src/utils/observability/Cargo.toml [hunk 1]
```diff
@@ -59,7 +59,9 @@ tracing-subscriber = { version = "0.3", features = [
 ] }
 pin-project-lite = { version = "0.2" }
 tower = { version = "0.5", default-features = false }
-tower-http = { version = "0.6", default-features = false }
+tower-http = { version = "0.6", default-features = false, features = [
```
Comment (s373r) [inline src/utils/observability/Cargo.toml:62]: `kamu-molecule-bridge`: after updating to v0.263.3, a build error occurred:

```
   Compiling observability v0.263.3 (https://github.com/kamu-data/kamu-cli?tag=v0.263.3#6124c907)
error[E0433]: failed to resolve: could not find `trace` in `tower_http`
   --> /home/s373r/.local/share/cargo/git/checkouts/kamu-cli-aacc64f87e73d763/6124c90/src/utils/observability/src/tonic.rs:12:36
    |
 12 | pub fn grpc_layer() -> tower_http::trace::TraceLayer<
    |                                    ^^^^^ could not find `trace` in `tower_http`
```
